// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RegisterFile(arg1) {
  return window['go']['media']['Service']['RegisterFile'](arg1);
}
