// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {cutter} from '../models';

export function Export(arg1:cutter.Request):Promise<string>;
