// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetKeyframes(arg1, arg2, arg3) {
  return window['go']['keyframes']['Service']['GetKeyframes'](arg1, arg2, arg3);
}
