// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['backend']['App']['Greet'](arg1);
}

export function SetDevToolsState(arg1) {
  return window['go']['backend']['App']['SetDevToolsState'](arg1);
}

export function ToggleDevTools() {
  return window['go']['backend']['App']['ToggleDevTools']();
}
