// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FileExists(arg1) {
  return window['go']['dialogs']['Service']['FileExists'](arg1);
}

export function OpenFile(arg1, arg2, arg3) {
  return window['go']['dialogs']['Service']['OpenFile'](arg1, arg2, arg3);
}

export function OpenMediaFiles(arg1) {
  return window['go']['dialogs']['Service']['OpenMediaFiles'](arg1);
}

export function OpenPath(arg1) {
  return window['go']['dialogs']['Service']['OpenPath'](arg1);
}

export function ReadTextFile(arg1) {
  return window['go']['dialogs']['Service']['ReadTextFile'](arg1);
}

export function RevealInExplorer(arg1) {
  return window['go']['dialogs']['Service']['RevealInExplorer'](arg1);
}

export function SaveFile(arg1, arg2, arg3, arg4) {
  return window['go']['dialogs']['Service']['SaveFile'](arg1, arg2, arg3, arg4);
}

export function SelectDirectory(arg1, arg2) {
  return window['go']['dialogs']['Service']['SelectDirectory'](arg1, arg2);
}

export function WriteTextFile(arg1, arg2) {
  return window['go']['dialogs']['Service']['WriteTextFile'](arg1, arg2);
}
