// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dialogs} from '../models';

export function FileExists(arg1:string):Promise<boolean>;

export function OpenFile(arg1:string,arg2:string,arg3:Array<dialogs.FileFilter>):Promise<string>;

export function OpenMediaFiles(arg1:string):Promise<Array<string>>;

export function OpenPath(arg1:string):Promise<void>;

export function ReadTextFile(arg1:string):Promise<string>;

export function RevealInExplorer(arg1:string):Promise<void>;

export function SaveFile(arg1:string,arg2:string,arg3:string,arg4:Array<dialogs.FileFilter>):Promise<string>;

export function SelectDirectory(arg1:string,arg2:string):Promise<string>;

export function WriteTextFile(arg1:string,arg2:string):Promise<void>;
