// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ffbin} from '../models';

export function GetStatus():Promise<ffbin.Status>;

export function SetCustomDir(arg1:string):Promise<ffbin.Status>;
