// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ffrun} from '../models';

export function CancelJob(arg1:string):Promise<void>;

export function ListJobs():Promise<Array<ffrun.Job>>;
