// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelJob(arg1) {
  return window['go']['ffrun']['JobsService']['CancelJob'](arg1);
}

export function ListJobs() {
  return window['go']['ffrun']['JobsService']['ListJobs']();
}
