// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {thumbs} from '../models';

export function GetThumbnails(arg1:string,arg2:Array<number>,arg3:number):Promise<Array<thumbs.Thumbnail>>;
