// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteProject(arg1:string):Promise<void>;

export function ProjectPath(arg1:string):Promise<string>;

export function ReadProject(arg1:string):Promise<string>;

export function WriteProject(arg1:string,arg2:string):Promise<void>;
