// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteProject(arg1) {
  return window['go']['project']['Service']['DeleteProject'](arg1);
}

export function ProjectPath(arg1) {
  return window['go']['project']['Service']['ProjectPath'](arg1);
}

export function ReadProject(arg1) {
  return window['go']['project']['Service']['ReadProject'](arg1);
}

export function WriteProject(arg1, arg2) {
  return window['go']['project']['Service']['WriteProject'](arg1, arg2);
}
