// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {tools} from '../models';

export function CaptureFrame(arg1:string,arg2:number,arg3:string):Promise<string>;

export function Detect(arg1:tools.DetectRequest):Promise<string>;

export function ExtractTracks(arg1:string,arg2:Array<tools.ExtractStream>,arg3:string,arg4:number):Promise<string>;

export function MergeFiles(arg1:tools.MergeRequest):Promise<string>;
