// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureFrame(arg1, arg2, arg3) {
  return window['go']['tools']['Service']['CaptureFrame'](arg1, arg2, arg3);
}

export function Detect(arg1) {
  return window['go']['tools']['Service']['Detect'](arg1);
}

export function ExtractTracks(arg1, arg2, arg3, arg4) {
  return window['go']['tools']['Service']['ExtractTracks'](arg1, arg2, arg3, arg4);
}

export function MergeFiles(arg1) {
  return window['go']['tools']['Service']['MergeFiles'](arg1);
}
