// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetWaveform(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number,arg6:string):Promise<string>;
